# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Minesweerper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'JSQMessagesViewController'

  # Pods for Minesweerper

  target 'MinesweerperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MinesweerperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
